import {rpc} from '@/lib/supabase';
'use client';
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {NativeSelect,NativeSelectOption} from '@/components/ui/native-select';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {STATIONS,formatScore,type Student,type Workshop,type Threshold} from '@/lib/grading';
type Data={workshops:Workshop[];selected:Workshop|null;students:Student[];thresholds:Threshold[]};
export default function TeacherDashboard(){
 const [data,setData]=useState<Data|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[editing,setEditing]=useState<Student|null>(null),[tab,setTab]=useState('roster');
 async function load(id?:string,signal?:AbortSignal){const result=await rpc<Data>('nptc_teacher_data',{requested_workshop:id??null},signal);setData(result);setEditing(null);return result as Data;}
 useEffect(()=>{const controller=new AbortController();load(undefined,controller.signal).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>controller.abort();},[]);
 async function changeWorkshop(id:string){setBusy(true);setError('');setMessage('');try{await load(id);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function save(payload:Record<string,unknown>,success:string){setBusy(true);setError('');setMessage('');try{const result=await rpc<{id?:string}>('nptc_teacher_write',{body:{...payload,workshopId:data?.selected?.id}});await load(result.id??data?.selected?.id);setMessage(success);return true;}catch(e){setError((e as Error).message);return false;}finally{setBusy(false);}}
 return <><div className="dashboard-title"><div><h1>教學評量管理</h1><p>建立名冊、登錄成績，讓回饋清楚抵達每位學員。</p></div><a href="/student" className="text-link">查看學員專區 ↗</a></div><div role="alert" className={error?'notice error':''}>{error}</div><div role="status" className={message?'notice success':''}>{message}</div>{!data?<section className="portal-panel"><p>{error?'資料載入失敗，請重試。':'正在載入學員與成績資料…'}</p>{error&&<Button className="action" onClick={()=>changeWorkshop('')}>重新載入</Button>}</section>:<>
 <div className="workshop-toolbar"><label>目前梯次<NativeSelect aria-label="選擇工作坊梯次" value={data.selected?.id??''} disabled={busy} onChange={e=>changeWorkshop(e.target.value)}>{!data.workshops.length&&<NativeSelectOption value="">尚未建立梯次</NativeSelectOption>}{data.workshops.map(w=><NativeSelectOption key={w.id} value={w.id}>{w.name}</NativeSelectOption>)}</NativeSelect></label><form className="new-workshop" onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;const f=new FormData(form);if(await save({action:'createWorkshop',name:f.get('name')},'新梯次已建立。'))form.reset();}}><Input name="name" aria-label="新梯次名稱" placeholder="新梯次名稱，例如：2026 秋季班" maxLength={100} required disabled={busy}/><Button className="action secondary" type="submit" disabled={busy}>建立梯次</Button></form></div>
 {!data.selected?<section className="empty-panel"><h2>先建立第一個工作坊梯次</h2><p>不同梯次的名冊、成績與邊緣及格分數會分開管理。</p></section>:<>
 <div className="management-stats"><article><span>本梯次學員</span><strong>{data.students.length}<small> 位</small></strong></article><article><span>每題固定及格分數</span><strong>60<small> / 100</small></strong></article><article><span>成績狀態</span><strong className="status-text">{data.selected.published?'已公布':'尚未公布'}</strong></article></div>
 <section className="threshold-panel"><div><h2>邊緣及格分數</h2><p>各題取本梯次 Global Rating＝3 的學員該題分數平均。無符合資料時不計算。</p></div><div className="threshold-grid">{STATIONS.map((s,i)=><div key={s.key}><span>第 {s.day} 天 · {s.title}</span><strong>{formatScore(data.thresholds[i]?.value??null)}</strong><small>{data.thresholds[i]?.count?`${data.thresholds[i].count} 位 Rating＝3 學員`:'尚無法計算'}</small></div>)}</div></section>
 <div className="publication-bar"><p>{data.selected.published?'成績已開放給本人查看。修改前請先撤回公布。':'名冊及成績目前僅老師可見，確認後再公布給學員。'}</p><Button disabled={busy} className="action secondary" onClick={()=>save({action:'publish',published:!data.selected!.published},data.selected!.published?'已撤回公布，現在可以編輯。':'成績已公布，學員可查看本人紀錄。')}>{data.selected.published?'撤回公布':'公布本梯次成績'}</Button></div>
 <Tabs value={tab} onValueChange={v=>{setTab(String(v));setEditing(null);setError('');setMessage('');}}><TabsList className="dashboard-tabs"><TabsTrigger value="roster" disabled={busy}>學員名冊</TabsTrigger><TabsTrigger value="scores" disabled={busy}>成績登錄</TabsTrigger></TabsList>
 <TabsContent value="roster"><div className="roster-layout"><section className="data-panel"><div className="panel-heading"><h2>學員名冊</h2><span>{data.students.length} 位學員</span></div>{data.students.length?<Table><TableHeader><TableRow><TableHead>學號</TableHead><TableHead>姓名 / 登入 Email</TableHead><TableHead>操作</TableHead></TableRow></TableHeader><TableBody>{data.students.map(s=><TableRow key={s.id}><TableCell>{s.code}</TableCell><TableCell>{s.name}<small className="cell-email">{s.email}</small></TableCell><TableCell><Button className="action small secondary" disabled={busy||!!data.selected?.published} onClick={()=>setEditing(s)}>編輯</Button></TableCell></TableRow>)}</TableBody></Table>:<p className="empty-inline">尚無學員，請新增第一位學員。</p>}</section><section className="data-panel"><h2>{editing?'編輯學員':'新增學員'}</h2><p className="form-help">登入 Email 必須與學員收取驗證信的信箱一致。</p><form key={editing?.id??'new'} className="entry-form" onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;const f=new FormData(form);if(await save({action:'saveStudent',id:editing?.id,revision:editing?.revision,name:f.get('name'),code:f.get('code'),email:f.get('email')},'學員資料已儲存。'))form.reset();}}><fieldset disabled={busy||!!data.selected.published}><label>學號<Input name="code" defaultValue={editing?.code??''} required maxLength={40} autoComplete="off"/></label><label>姓名<Input name="name" defaultValue={editing?.name??''} required maxLength={100} autoComplete="off"/></label><label>登入 Email<Input name="email" type="email" defaultValue={editing?.email??''} required maxLength={254} autoComplete="off"/></label><div className="form-actions"><Button className="action" type="submit">{busy?'儲存中…':'儲存學員資料'}</Button>{editing&&<Button className="action secondary" onClick={()=>setEditing(null)}>取消</Button>}</div></fieldset></form></section></div></TabsContent>
 <TabsContent value="scores"><section className="data-panel"><div className="panel-heading"><div><h2>四題成績總覽</h2><p className="form-help">分數／Global Rating；「—」代表尚未登錄。</p></div></div>{data.students.length?<Table><TableHeader><TableRow><TableHead>學員</TableHead>{STATIONS.map(s=><TableHead key={s.key}>第 {s.day} 天 · {s.title}</TableHead>)}<TableHead>操作</TableHead></TableRow></TableHeader><TableBody>{data.students.map(s=><TableRow key={s.id}><TableCell>{s.name}<small className="cell-email">{s.code}</small></TableCell>{STATIONS.map(({key})=><TableCell key={key}>{formatScore(s[`${key}_score`] as number|null)} <span className="dim">/ {s[`${key}_rating`]??'—'}</span></TableCell>)}<TableCell><Button className="action small secondary" disabled={busy||!!data.selected?.published} onClick={()=>setEditing(s)}>登錄分數</Button></TableCell></TableRow>)}</TableBody></Table>:<p className="empty-inline">請先在「學員名冊」新增學員。</p>}</section>
 {editing&&<section className="data-panel score-editor"><div className="panel-heading"><div><span className="section-label">SCORE ENTRY</span><h2>{editing.name} · {editing.code}</h2></div><Button className="action secondary" disabled={busy} onClick={()=>setEditing(null)}>取消編輯</Button></div><form key={`${editing.id}-${editing.revision}`} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);const grades=Object.fromEntries(STATIONS.map(({key})=>[key,{score:f.get(`${key}_score`)===''?null:Number(f.get(`${key}_score`)),rating:f.get(`${key}_rating`)===''?null:Number(f.get(`${key}_rating`))}]));save({action:'saveScores',id:editing.id,revision:editing.revision,grades},'四題成績已儲存，邊緣及格分數已重新計算。');}}><fieldset disabled={busy||!!data.selected.published}><div className="score-input-grid">{STATIONS.map(s=><div className="score-input-card" key={s.key}><h3>第 {s.day} 天 · {s.title}</h3><label>OSCE 分數（0–100）<Input name={`${s.key}_score`} type="number" min={0} max={100} step="any" defaultValue={editing[`${s.key}_score`]??''}/></label><label>Global Rating（1–5）<NativeSelect name={`${s.key}_rating`} defaultValue={editing[`${s.key}_rating`]??''}><NativeSelectOption value="">尚未評分</NativeSelectOption>{[1,2,3,4,5].map(n=><NativeSelectOption key={n} value={n}>{n}{n===3?' · 納入邊緣分數計算':''}</NativeSelectOption>)}</NativeSelect></label></div>)}</div><p className="form-help">每題分數與 Rating 請成對填寫；兩欄都留空可清除該題紀錄。及格判定依固定 60 分，邊緣及格分數另外呈現。</p><Button type="submit" className="action" disabled={busy}>{busy?'儲存中…':'儲存四題成績'}</Button></fieldset></form></section>}
 </TabsContent></Tabs></>}
 </>}</>;
}

