import assert from 'node:assert/strict';
import {DOMAINS,domainTotal,validateDomainMax,validateDomainScores,radarValues,domainFormValues} from '../lib/domains.ts';
const max={currentHistory:30,pastHistory:15,ros:15,physicalExam:25,differentialDiagnosis:15};
const score={currentHistory:24,pastHistory:9,ros:12,physicalExam:20,differentialDiagnosis:12};
assert.equal(domainTotal(validateDomainScores(score,max)),77);
assert.deepEqual(radarValues(score,max),[4,3,4,4,4]);
assert.deepEqual(radarValues(max,max),[5,5,5,5,5]);
assert.deepEqual(radarValues(Object.fromEntries(DOMAINS.map(d=>[d.key,0])),max),[0,0,0,0,0]);
assert.equal(radarValues(null,max),null);
assert.equal(radarValues(score,null),null);
assert.throws(()=>validateDomainMax({...max,ros:14}));
assert.throws(()=>validateDomainMax({...max,ros:0,currentHistory:45}));
assert.throws(()=>validateDomainScores({...score,physicalExam:26},max));
assert.throws(()=>validateDomainScores({...score,ros:NaN},max));
assert.throws(()=>validateDomainScores({...score,ros:1.123},max));
const form=new FormData();assert.equal(domainFormValues(form,'a'),null);
form.set('a_ros','0');assert.throws(()=>domainFormValues(form,'a'));
DOMAINS.forEach(d=>form.set(`a_${d.key}`,String(score[d.key])));assert.deepEqual(domainFormValues(form,'a'),score);
console.log('PASS: domain totals, limits, null vs zero, partial inputs and normalized radar');
